# Generated by Django 4.1.7 on 2023-03-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size',
            new_name='SizeVarient',
        ),
    ]
